### ISSUE TITLE
Use SYNTHIA dataset

### ISSUE THREAD

**Issue by ruizhaoz** [jxhuang0508/CVRN#2]
Hello, this CVRN is a very interesing work. I am wondering how do you use SYHTHIA dataset in the experiments. Could you share like which verision of SYNTHIA dataset do you use and the format and some prepocessing steps you used in the experiments? Thanks in advance!

**Comment by jxhuang0508** [comment]
Hi, we have uploaded the data loaders (for all datasets) and label conversion files (SYNTHIA to COCO style), under 'data loader and processing' directory.

We used the SYNTHIA-RAND-CITYSCAPES which contains 9400 images. You could follow ADVENT (https://github.com/valeoai/ADVENT) to prepare the datasets and use our provided files to convert SYNTHIA label into panoptic segmentation (COCO style).
