### ISSUE TITLE
Mapillary labels into Cityscapes label conversion 

### ISSUE THREAD

**Issue by susaha** [jxhuang0508/CVRN#4]
Mapillary labels into Cityscapes label conversion 

Dear author, thank you for providing the code!

The following script converts Mapillary labels into Cityscapes label space: CVRN/data loader and processing/init_vistas2cityscapes_format.py.

I have a question here. This code takes the semantic ground truth label files (in PNG format) as inputs. The original label PNG files of Maipillary are three-channel color PNG images. By looking at your code :
https://github.com/jxhuang0508/CVRN/blob/cea4fec271d6a6d3f57d496113099024887a7e92/data%20loader%20and%20processing/init_vistas2cityscapes_format.py#L20
and
https://github.com/jxhuang0508/CVRN/blob/cea4fec271d6a6d3f57d496113099024887a7e92/data%20loader%20and%20processing/init_vistas2cityscapes_format.py#L58-L61
, it seems we need a one-channel PNG semantic label file as input instead of three-channel color semantic labels.
Could you please let me know how you converted the Mapillary color semantic label images to single-channel label PNG files?
Is there any RGB to id encoding scheme you are using for that?

**Comment by jxhuang0508** [comment]
Hi,

As far as I can remember, Mapillary dataset provided ''Train ID'' ground-truth (one-channel maps) in addition to ''Color'' ground-truth. With the provided ''Train ID'' ground-truth, we can use the label conversion file to convert it into CItyscapes style.

**Comment by susaha** [comment]
@jxhuang0508 : Thanks a lot for uploading the scripts for conversion! Much appreciated!
