### ISSUE TITLE
ModuleNotFoundError: No module named 'upsnet.operators.functions.entropy_loss'

### ISSUE THREAD

**Issue by krumo** [jxhuang0508/CVRN#8]
Hi, when I run your code, I encounter the following error:

> Traceback (most recent call last):
  File "upsnet/upsnet_end2end_train.py", line 61, in <module>
    from upsnet.models import *
  File "upsnet/../upsnet/models/__init__.py", line 2, in <module>
    from .resnet_upsnet_multiscale_branch_lr10 import resnet_101_upsnet_multiscale_branch_lr10, resnet_50_upsnet_multiscale_branch_lr10
  File "upsnet/../upsnet/models/resnet_upsnet_multiscale_branch_lr10.py", line 20, in <module>
    from upsnet.operators.functions.entropy_loss import prob_2_entropy, sigmoid_2_entropy, entropy_loss
ModuleNotFoundError: No module named 'upsnet.operators.functions.entropy_loss'

It seems that there is no a module called `entropy_loss` under the `upsnet.operators.functions`. I cannot find this module under your repo or original UPSNet repo. Could you help me solve it? Thanks in advance!

**Comment by jxhuang0508** [comment]
Hi, 

Thanks for your interests! I have uploaded the entropy_loss file in the following location:
https://github.com/jxhuang0508/CVRN/blob/570743d52d4413cfceb50b1c186e43b98200a7e6/entropt_loss_file/entropy_loss.py
